#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os, json, glob, pickle
from pathlib import Path
import pandas as pd
import numpy as np

from rdkit import Chem
from rdkit.Chem import AllChem, Draw
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit import RDLogger
RDLogger.DisableLog('rdApp.*')  # silence RDKit console spam

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.metrics import r2_score
import joblib
import argparse

# =========================
# -------- Helpers --------
# =========================

def ensure_dir(p):
    Path(p).mkdir(parents=True, exist_ok=True)

def save_caption(fig_path, caption, source="Generated by the author using scikit-learn, RDKit, and matplotlib."):
    cap_path = Path(fig_path).with_name("captions.txt")
    with open(cap_path, "a") as f:
        f.write(f"{Path(fig_path).name}: {caption}\nSource: {source}\n\n")

def fp_from_smiles(smiles, radius=2, nBits=2048):
    m = Chem.MolFromSmiles(smiles)
    if m is None:
        return None
    fp = AllChem.GetMorganFingerprintAsBitVect(m, radius, nBits=nBits)
    vec = np.zeros(nBits, dtype=np.float32)
    for b in fp.GetOnBits():
        vec[b] = 1.0
    return vec

def newest_subdir(root: Path):
    subs = [p for p in root.glob("*") if p.is_dir()]
    if not subs:
        raise FileNotFoundError(f"No subdirectories found under {root}")
    subs.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return subs[0]

def latest_matching(run_dir: Path, patterns):
    """Return newest file in run_dir that matches any of the relative patterns."""
    best = None
    for pat in patterns:
        for p in run_dir.glob(pat):
            if best is None or p.stat().st_mtime > best.stat().st_mtime:
                best = p
    return best

def scatter_with_fit(ax, x, y, title, xlabel, ylabel):
    ax.scatter(x, y, s=10, alpha=0.6)
    coeffs = np.polyfit(x, y, 1)
    xfit = np.linspace(np.min(x), np.max(x), 100)
    yfit = coeffs[0]*xfit + coeffs[1]
    ax.plot(xfit, yfit, linewidth=1.5)
    r2 = r2_score(y, np.polyval(coeffs, x))
    ax.set_title(f"{title}\n$R^2$ = {r2:.3f}")
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.grid(True, linestyle=":", linewidth=0.5)
    return r2

def read_json_if_exists(p: Path):
    if p and p.is_file():
        return json.loads(p.read_text())
    return None

def get_col(df, names):
    for n in names:
        if df is not None and n in df.columns:
            return df[n].dropna().values
    return None

def get_series(df, names):
    for n in names:
        if df is not None and n in df.columns:
            return df[n]
    return None

def smiles_for_depict(s: str) -> str:
    # Keep polymer wildcards explicit so they render: "*" -> "[*]"
    return s.replace("*", "[*]")

def load_estimator(pathlike):
    obj = joblib.load(str(Path(pathlike).expanduser()))
    if isinstance(obj, dict):
        est = obj.get("model", obj.get("estimator", obj))
    elif isinstance(obj, (list, tuple)):
        est = obj[0]
    else:
        est = obj
    if not hasattr(est, "predict"):
        raise TypeError(f"{pathlike} did not load to a scikit-learn estimator.")
    return est

# ---------- Descriptor helpers for Fig 2 ----------

def find_scaler_and_meta(proj_root: Path, runs_root: Path):
    # Preferred: retrained models folder
    candidates = []
    retrained = proj_root / "2Predictors" / "Retrained" / "models"
    if retrained.is_dir():
        candidates.append(retrained)

    # Fallback: newest models_snapshot under Runs/*/<models_snapshot>
    snapshots = sorted((p for p in runs_root.glob("*/*") if p.name == "models_snapshot"),
                       key=lambda p: p.stat().st_mtime, reverse=True)
    candidates.extend(snapshots)

    for p in candidates:
        sp = p / "desc_scaler.pkl"
        mp = p / "metadata.json"
        if sp.is_file():
            return sp, (mp if mp.is_file() else None)
    return None, None

def load_feature_order(meta_path: Path, df_desc: pd.DataFrame):
    if meta_path and meta_path.is_file():
        try:
            J = json.loads(meta_path.read_text())
            for key in ["feature_names", "desc_names", "descriptor_names"]:
                if key in J and isinstance(J[key], list) and len(J[key]) > 0:
                    return [c for c in J[key] if c in df_desc.columns]
        except Exception:
            pass
    ban = {"SMILES", "smiles", "Tg", "Tg_C", "tg", "tg_c", "MAC", "MAC_cm2_g", "mac", "mac_cm2_g"}
    return [c for c in df_desc.columns if c not in ban]

def build_descriptor_matrix_for_training(proj_root: Path, train_df: pd.DataFrame, smiles_col: str):
    cache_path = proj_root / "data" / "desc_cache.csv"
    if not cache_path.is_file():
        return None, None
    df_desc = pd.read_csv(cache_path)
    desc_smi = "SMILES" if "SMILES" in df_desc.columns else ("smiles" if "smiles" in df_desc.columns else None)
    if desc_smi is None:
        return None, None
    merged = pd.merge(train_df, df_desc, left_on=smiles_col, right_on=desc_smi, how="inner")
    if len(merged) == 0:
        return None, None
    return merged, df_desc

# =========================
# ---------- CLI ----------
# =========================
ap = argparse.ArgumentParser()
ap.add_argument("--proj_root", required=True, help="PolymerDesign project root")
ap.add_argument("--runs_root", required=True, help="Runs root directory with generation rounds")
ap.add_argument("--run_dir", required=False, help="Specific run folder; if omitted, use newest under runs_root")
ap.add_argument("--tg_model", required=False, help="Pickle path for Tg surrogate")
ap.add_argument("--mac_model", required=False, help="Pickle path for MAC surrogate")
ap.add_argument("--fp_bits", type=int, default=2048)
ap.add_argument("--fp_radius", type=int, default=2)
# optional: override lead SMILES via comma-separated string
ap.add_argument("--lead_smiles", type=str, default=None,
               help="Comma-separated list of 3 SMILES to depict as leads.")
args = ap.parse_args()

PROJ = Path(args.proj_root).expanduser()
RUNS = Path(args.runs_root).expanduser()
RUN_DIR = Path(args.run_dir).expanduser() if args.run_dir else newest_subdir(RUNS)

FIGDIR = PROJ / "assets" / "Figures2"
ensure_dir(FIGDIR)

print(f"[INFO] Using run: {RUN_DIR}")

# =========================
# ---- File discovery -----
# =========================

# Training CSV for surrogate sanity check
train_csv_candidates = [
    PROJ / "1Dataset" / "PI1M_with_Tg_Final.csv",
    PROJ / "1Dataset" / "PI1M_Tg_MAC.csv",
]
train_csv = next((p for p in train_csv_candidates if p.is_file()), None)

# Per-run data (choose newest file in this run for each role)
generated_csv = latest_matching(RUN_DIR, ["predicted.csv", "polymer_candidates.csv"])
hits_csv      = latest_matching(RUN_DIR, ["hits.csv", "final_hits.csv"])
summary_json  = latest_matching(RUN_DIR, ["summary.json"])

gen_df = pd.read_csv(generated_csv) if generated_csv else None
hits_df = pd.read_csv(hits_csv) if hits_csv else None

# =========================
# -- Figure 2: Surrogate --
# =========================
if train_csv is None:
    print("[Fig2] Could not find training CSV. Looked in:", [str(p) for p in train_csv_candidates])
else:
    df = pd.read_csv(train_csv)
    smiles_col = "SMILES" if "SMILES" in df.columns else ("smiles" if "smiles" in df.columns else None)
    tg_col = next((c for c in ["Tg","Tg_C","tg","tg_c"] if c in df.columns), None)
    mac_col = next((c for c in ["MAC","MAC_cm2_g","mac","mac_cm2_g"] if c in df.columns), None)

    if smiles_col is None:
        print("[Fig2] No SMILES column found in training CSV.")
    else:
        tg_model = load_estimator(args.tg_model) if args.tg_model and Path(args.tg_model).is_file() else None
        mac_model = load_estimator(args.mac_model) if args.mac_model and Path(args.mac_model).is_file() else None

        if (tg_model is not None) or (mac_model is not None):
            scaler_path, meta_path = find_scaler_and_meta(PROJ, RUNS)
            merged, df_desc = build_descriptor_matrix_for_training(PROJ, df, smiles_col)

            X, dff, used_mode = None, None, None
            if scaler_path and (merged is not None):
                try:
                    scaler = joblib.load(scaler_path)
                    feat_order = load_feature_order(meta_path, df_desc)
                    if len(feat_order) == 0:
                        raise RuntimeError("No descriptor feature list found.")
                    Z = merged[feat_order].replace([np.inf, -np.inf], np.nan).dropna(axis=0, how="any")
                    dff = merged.loc[Z.index].reset_index(drop=True)
                    X = scaler.transform(Z.values)
                    used_mode = "descriptors"
                    print(f"[Fig2] Using descriptors: {len(feat_order)} features | rows: {X.shape[0]} | scaler: {scaler_path}")
                except Exception as e:
                    print(f"[Fig2] Descriptor path failed ({e}); falling back to Morgan fingerprints.")

            if X is None:
                print("[Fig2] Computing Morgan fingerprints for surrogate validation…")
                fps, keep_idx = [], []
                smi_series = df[smiles_col].astype(str)
                for i, s in enumerate(smi_series):
                    vec = fp_from_smiles(s, radius=args.fp_radius, nBits=args.fp_bits)
                    if vec is not None:
                        fps.append(vec); keep_idx.append(i)
                if len(fps):
                    X = np.vstack(fps)
                    dff = df.iloc[keep_idx].reset_index(drop=True)
                    used_mode = "fingerprints"
                    print(f"[Fig2] FP matrix shape: {X.shape}  (radius={args.fp_radius}, bits={args.fp_bits})")

            fig, axs = plt.subplots(1, 2, figsize=(10,4))
            made_any = False
            if (X is not None) and (dff is not None):
                if (tg_model is not None) and (tg_col is not None) and (tg_col in dff.columns):
                    try:
                        y_true = dff[tg_col].values
                        y_pred = tg_model.predict(X)
                        scatter_with_fit(axs[0], y_true, y_pred, "Tg surrogate", "Actual Tg (°C)", "Predicted Tg (°C)")
                        made_any = True
                    except Exception as e:
                        axs[0].axis('off'); axs[0].text(0.5,0.5,f"Tg predict error:\n{e}", ha='center')
                else:
                    axs[0].axis('off'); axs[0].text(0.5,0.5,"No Tg model/labels", ha='center')

                if (mac_model is not None) and (mac_col is not None) and (mac_col in dff.columns):
                    try:
                        y_true = dff[mac_col].values
                        y_pred = mac_model.predict(X)
                        scatter_with_fit(axs[1], y_true, y_pred, "MAC surrogate", "Actual MAC (cm²/g)", "Predicted MAC (cm²/g)")
                        made_any = True
                    except Exception as e:
                        axs[1].axis('off'); axs[1].text(0.5,0.5,f"MAC predict error:\n{e}", ha='center')
                else:
                    axs[1].axis('off'); axs[1].text(0.5,0.5,"No MAC model/labels", ha='center')
            else:
                axs[0].axis('off'); axs[0].text(0.5,0.5,"No features available", ha='center')
                axs[1].axis('off'); axs[1].text(0.5,0.5,"No features available", ha='center')

            plt.tight_layout()
            out = FIGDIR / "fig2_surrogate_validation.png"
            plt.savefig(out, dpi=300); plt.close()
            if made_any:
                save_caption(out, f"Surrogate model validation ({used_mode}) on training set with regression line.")

# ===================================
# -- Gather generated & hits counts --
# ===================================

generated = valid = hits = None

# Prefer summary.json if present
J = read_json_if_exists(summary_json) if summary_json else None
if J:
    generated = int(J.get("generated_total", J.get("n_generated", 0)))
    valid     = int(J.get("valid_total",     J.get("n_valid", 0)))
    hits      = int(J.get("hits_total",      J.get("n_hits", 0)))

# Fallbacks from files
if gen_df is not None:
    if generated is None: generated = int(len(gen_df))
    if valid is None:
        for c in ["is_valid","valid","rdkit_valid"]:
            if c in gen_df.columns:
                valid = int(gen_df[c].sum()); break
        if valid is None: valid = generated
if hits_df is not None and hits is None:
    hits = int(len(hits_df))

# ================================
# -- Fig 3: Conditional Steering --
# ================================
if gen_df is None:
    print("[Fig3] Could not find generated CSV in run:", RUN_DIR)
else:
    mac_ctrl = get_series(gen_df, ["control_mac","mac_ctrl","mac_token","ctrl_mac"])
    mac_pred = get_series(gen_df, ["pred_mac","mac_pred","MAC_pred"])
    tg_ctrl  = get_series(gen_df, ["control_tg","tg_ctrl","tg_token","ctrl_tg"])
    tg_pred  = get_series(gen_df, ["pred_tg","tg_pred","Tg_pred"])

    fig, axs = plt.subplots(2, 1, figsize=(6,7))
    shown_any = False

    if mac_ctrl is not None and mac_pred is not None:
        axs[0].scatter(mac_ctrl, mac_pred, s=8, alpha=0.6)
        axs[0].set_title("MAC control token vs predicted MAC")
        axs[0].set_xlabel("MAC control"); axs[0].set_ylabel("Predicted MAC")
        axs[0].grid(True, linestyle=":", linewidth=0.5)
        shown_any = True
    else:
        axs[0].axis('off'); axs[0].text(0.5,0.5,"No MAC control/pred columns", ha='center')

    if tg_ctrl is not None and tg_pred is not None:
        axs[1].scatter(tg_ctrl, tg_pred, s=8, alpha=0.6)
        axs[1].set_title("Tg control token vs predicted Tg")
        axs[1].set_xlabel("Tg control"); axs[1].set_ylabel("Predicted Tg (°C)")
        axs[1].grid(True, linestyle=":", linewidth=0.5)
        shown_any = True
    else:
        axs[1].axis('off'); axs[1].text(0.5,0.5,"No Tg control/pred columns", ha='center')

    plt.tight_layout()
    out = FIGDIR / "fig3_conditional_steering.png"
    plt.savefig(out, dpi=300); plt.close()
    if shown_any:
        save_caption(out, "Monotonic response of predicted properties to control tokens for MAC and Tg.")

# ===================================
# -- Fig 4: Selection Funnel (run) --
# ===================================
stages = []
if J:
    for k in ["generated_total","valid_total","unique_total","clusters_total","hits_total"]:
        if k in J:
            stages.append((k.replace("_total",""), int(J[k])))

if len(stages) == 0 and gen_df is not None:
    # derive from present files in this run
    mapping = [
        ("generated", ["generated.csv","generated.smi","polymer_candidates.csv","predicted.csv"]),
        ("valid",     ["valid.csv","valid.smi","valid_with_desc.csv"]),
        ("unique",    ["unique.csv","unique.smi"]),
        ("clusters",  ["clustered_candidates.csv","clusters.csv"]),
        ("hits",      ["hits.csv","final_hits.csv"]),
    ]
    for name, pats in mapping:
        count = None
        for pat in pats:
            fp = RUN_DIR / pat
            if fp.is_file():
                if fp.suffix == ".csv":
                    try: count = len(pd.read_csv(fp))
                    except: count = None
                else:
                    try: count = sum(1 for _ in open(fp))
                    except: count = None
                if count is not None:
                    break
        if count is not None:
            stages.append((name, int(count)))

if len(stages):
    fig, ax = plt.subplots(figsize=(7,5))
    ax.set_axis_off()
    total = stages[0][1]
    x0, y0 = 0.1, 0.9
    h = 0.1
    for i, (name, cnt) in enumerate(stages):
        width = 0.8 * (cnt / max(1,total))
        ax.add_patch(plt.Rectangle((0.1, y0 - i*(h+0.03)), width, h, fill=False))
        pct = (100.0 * cnt / max(1,total))
        ax.text(0.11, y0 - i*(h+0.03) + h/2, f"{name}: {cnt} ({pct:.1f}%)", va="center")
    out = FIGDIR / "fig4_selection_funnel.png"
    plt.savefig(out, dpi=300, bbox_inches="tight"); plt.close()
    save_caption(out, f"Selection funnel for run {RUN_DIR.name} with stage counts and retention percentages.")

# ======================================
# -- Fig 5: Chemical Diversity (PCA)  --
# ======================================
def collect_smiles(df, colnames=("SMILES","smiles")):
    for c in colnames:
        if df is not None and c in df.columns:
            return df[c].dropna().astype(str).tolist()
    return []

train_smi = []
if train_csv:
    train_df = pd.read_csv(train_csv)
    train_smi = collect_smiles(train_df)

gen_smi = collect_smiles(gen_df)
hits_smi = collect_smiles(hits_df)

def fps_matrix(smiles_list, radius, bits):
    vecs = []
    for s in smiles_list:
        v = fp_from_smiles(s, radius=radius, nBits=bits)
        if v is not None:
            vecs.append(v)
    if len(vecs):
        return np.vstack(vecs)
    return None

X_train = fps_matrix(train_smi, args.fp_radius, args.fp_bits) if len(train_smi) else None
X_gen   = fps_matrix(gen_smi,   args.fp_radius, args.fp_bits) if len(gen_smi)   else None
X_hits  = fps_matrix(hits_smi,  args.fp_radius, args.fp_bits) if len(hits_smi)  else None

mats = [m for m in [X_train, X_gen, X_hits] if m is not None and m.size>0]
if len(mats):
    X_all = np.vstack(mats)
    pca = PCA(n_components=2, random_state=42)
    coords = pca.fit_transform(X_all)

    n_tr = X_train.shape[0] if X_train is not None else 0
    n_ge = X_gen.shape[0]   if X_gen   is not None else 0

    i0 = 0
    tr_xy = coords[i0:i0+n_tr] if n_tr else None
    i0 += n_tr
    ge_xy = coords[i0:i0+n_ge] if n_ge else None
    i0 += n_ge
    hi_xy = coords[i0:] if X_hits is not None else None

    plt.figure(figsize=(6,5))
    if tr_xy is not None:
        plt.scatter(tr_xy[:,0], tr_xy[:,1], s=6, alpha=0.25, label="Training", zorder=1)
    if ge_xy is not None:
        plt.scatter(ge_xy[:,0], ge_xy[:,1], s=8, alpha=0.5, label="Generated", zorder=2)
    if hi_xy is not None:
        plt.scatter(hi_xy[:,0], hi_xy[:,1], s=60, alpha=0.9, marker="*", label="Top hits", zorder=3)
    plt.legend()
    plt.title("Chemical diversity map (PCA of Morgan fingerprints)")
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.grid(True, linestyle=":", linewidth=0.5)
    out = FIGDIR / "fig5_diversity_map.png"
    plt.savefig(out, dpi=300, bbox_inches="tight"); plt.close()
    save_caption(out, "Training, generated, and top hits in 2D fingerprint space (PCA).")

# ======================================
# -- Fig 6: Property Distributions    --
# ======================================
def boxplot_three(ax, train_vals, gen_vals, hit_vals, title, ylab, thresholds=None):
    data, labels = [], []
    if train_vals is not None and len(train_vals): data.append(train_vals); labels.append("Training")
    if gen_vals   is not None and len(gen_vals):   data.append(gen_vals);   labels.append("All generated")
    if hit_vals   is not None and len(hit_vals):   data.append(hit_vals);   labels.append("Top hits")
    if len(data) == 0:
        ax.axis('off'); ax.text(0.5,0.5,"No data", ha='center'); return
    ax.boxplot(data, labels=labels, showfliers=False)
    ax.set_title(title); ax.set_ylabel(ylab); ax.grid(True, linestyle=":", linewidth=0.5)
    if thresholds:
        for t in thresholds: ax.axhline(t, linestyle="--", linewidth=1)

if train_csv or gen_df is not None:
    tg_train  = get_col(train_df if train_csv else None, ["Tg","Tg_C","tg","tg_c"])
    mac_train = get_col(train_df if train_csv else None, ["MAC","MAC_cm2_g","mac","mac_cm2_g"])

    tg_gen  = get_col(gen_df,  ["pred_tg","tg_pred","Tg_pred"])
    mac_gen = get_col(gen_df,  ["pred_mac","mac_pred","MAC_pred"])
    tg_hits = get_col(hits_df, ["pred_tg","tg_pred","Tg_pred"])
    mac_hits= get_col(hits_df, ["pred_mac","mac_pred","MAC_pred"])

    fig, axs = plt.subplots(1, 2, figsize=(10,4))
    boxplot_three(axs[0], tg_train, tg_gen, tg_hits, "Tg distributions", "Tg (°C)")
    boxplot_three(axs[1], mac_train, mac_gen, mac_hits, "MAC distributions", "MAC (cm²/g)")
    plt.tight_layout()
    out = FIGDIR / "fig6_distributions.png"
    plt.savefig(out, dpi=300); plt.close()
    save_caption(out, "Distribution comparison for Tg and MAC across training, generated, and top hits.")

# ======================================
# -- Fig 7: Highlighted Lead Structures
# ======================================
if args.lead_smiles:
    lead_smiles = [s.strip() for s in args.lead_smiles.split(",") if s.strip()]
else:
    # Your three specific leads:
    lead_smiles = [
        "*C(=O)Nc1ccc(*)nc1O",           # pyridine-phenol amide -> benzoxazole upgrade
        "*C(=O)Nc1ccc(*)nc1C(=O)O",      # amide + ring carboxyl -> dianhydride -> polyimide
        "*C(=O)Nc1ccc(*)c(O)c1O",        # catechol amide -> benzoxazole/polyimide path
    ]

lead_labels = [
    "Pyridine–phenol amide\n(benzoxazole upgrade)",
    "Amide + ring carboxyl\n(dianhydride→polyimide)",
    "Catechol amide\n(benzoxazole / polyimide)",
]

mols = []
for s in lead_smiles:
    m = Chem.MolFromSmiles(smiles_for_depict(s))
    if m is None:
        raise ValueError(f"Bad SMILES: {s}")
    Chem.Kekulize(m, clearAromaticFlags=True)
    AllChem.Compute2DCoords(m)
    mols.append(m)

# Render as a clean strip with captions
if mols:
    n = len(mols)
    fig = plt.figure(figsize=(3.5*n, 3.0))
    for i, (m,lbl) in enumerate(zip(mols, lead_labels), 1):
        ax = fig.add_subplot(1, n, i)
        d = rdMolDraw2D.MolDraw2DCairo(430, 260)
        rdMolDraw2D.PrepareAndDrawMolecule(d, m)
        d.FinishDrawing()
        import io, PIL.Image as Image
        im = Image.open(io.BytesIO(d.GetDrawingText()))
        ax.imshow(im)
        ax.set_title(f"Lead {i}", pad=8, fontsize=12)
        ax.set_xlabel(lbl, fontsize=10)
        ax.set_xticks([]); ax.set_yticks([]); ax.set_frame_on(False)
    fig.suptitle("Highlighted lead candidates", fontsize=14)
    out = FIGDIR / "fig7_leads.png"
    plt.savefig(out, dpi=300, bbox_inches="tight"); plt.close()
    save_caption(out, "Three highlighted lead candidates with proposed upgrade routes (labels under each structure).")

# ======================================
# -- Fig 7b: Closed-loop Convergence  --
# ======================================
run_metrics = []
for mpath in RUNS.glob("*/summary.json"):
    JJ = read_json_if_exists(mpath)
    if JJ and ("success_rate" in JJ or ("hits_total" in JJ and "generated_total" in JJ)):
        rname = mpath.parent.name
        sr = JJ.get("success_rate", None)
        if sr is None and JJ.get("generated_total", 0):
            sr = float(JJ.get("hits_total", 0)) / float(JJ["generated_total"])
        if sr is not None:
            run_metrics.append((rname, float(sr)))

if len(run_metrics):
    def keyer(t):
        name = t[0]
        digits = "".join([c for c in name if c.isdigit()])
        try:  return int(digits) if digits else name
        except: return name
    run_metrics.sort(key=keyer)
    xs = list(range(1, len(run_metrics)+1))
    ys = [t[1] for t in run_metrics]
    plt.figure(figsize=(6,4))
    plt.plot(xs, ys, marker="o")
    plt.xlabel("Generation round")
    plt.ylabel("Success rate")
    plt.title("Closed-loop convergence across rounds")
    plt.grid(True, linestyle=":", linewidth=0.5)
    out = FIGDIR / "fig7b_convergence.png"
    plt.savefig(out, dpi=300, bbox_inches="tight"); plt.close()
    save_caption(out, "Closed-loop success rate by generation round, showing improvement over iterations.")
